# ========================================================
# Options: "baseline", "auxiliary", "intrinsic", "circle_only"
# ========================================================
strategy: "auxiliary" 

NITC: true
nitc_loss_weight: 1.0
softlabel_ratio: 0.0

MVS: true   

CIR: true   
circle_loss_weight: 0.1  

circle_margin: 0.25    
circle_gamma: 128    

CITC: true  
citc_inmodal_weight: 0.25
citc_intermodal_weight: 0.25
citc_loss_weight: 0.1    

SS: true    
simclr_temperature: 0.1
ss_loss_weight: 0.4

ID: false   
id_loss_weight: 0.0

SDM: false
sdm_loss_weight: 0.0

MLM: false
mlm_loss_weight: 1.0
cmt_depth: 4

RITC: false
ritc_eps: 1.0e-2
ritc_loss_weight: 1.0